# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigIntegerField(default=helpers.models.getid, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modification time')),
                ('depot', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='JSON Depot')),
                ('name', models.CharField(max_length=256)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=256, populate_from=['name'])),
            ],
            options={
                'db_table': 'things',
            },
        ),
    ]
